### ISSUE TITLE
Please do not verbatim-copy JOML code

### ISSUE THREAD

**Issue by httpdigest** [elect86/Jglm#2]
The Mat4d class is almost a verbatim copy of JOML's Matrix4f, including the JavaDocs, whose references do not match anymore, because glm just renamed the class and method names.

Examples:
JOML 1.7.1: https://github.com/JOML-CI/JOML/blob/5b9b0c0aa7e374dba08cfca4fe47bdd9c8cc6d03/src/org/joml/Matrix4f.java#L7283-L7300

glm: https://github.com/java-graphics/glm/blob/1431993cd0099cdd6666028faf65f0c1d38a5940/glm/src/glm/mat/_4/d/Mat4d.java#L361-L381

If you want to copy code and even JavaDoc verbatim, then you should at least give credit or ask for permission.

**Comment by ghost** [comment]
I completely agree with httpdigest, not giving credit is neither professional nor respectful.

**Comment by elect86** [comment]
Sorry sorry sorry, you are right, I should't have done that!

That's the problem when you are overloaded of work and you copy paste lazily a method surely working just to get a bug fixed (and then for the same laziness you finish to do the same for almost the whole class..) and postpone to give credits or find what the bug was. I did that when I opened that issue about the normalization input vector... I don't know if you remember

However I modified quickly the readme to give you asap credits and put a quick fix at this issue

I'll go tomorrow through the code, because there are also a couple of other methods in the `Glm` from joml

Please again sorry, Kai, I really didn't mean to provoke this. I don't know if this has the same meaning in english, but I completely did that in good faith (remember when I contributed a little to joml), with no bad intentions

**Comment by httpdigest** [comment]
Alright, then. No worries. :) I appreciate your response.

**Comment by elect86** [comment]
Oh nice, I am glad you appreciated :)

I removed some unused methods coming from joml and modified again the readme writing explicitly "Credits:" and listing the joml methods I left there... I'd like to ask you if I may keep those remaining methods until I manage to review with calm the whole class

Ps: let me offer you a drink :p

**Comment by httpdigest** [comment]
Hey, what's up. Just one thing:

> and return the object itself in order to concatenate operations

You don't have to go overboard with credits for API design concepts that no one did _invent_ and should claim credit for. :) Actually, now I feel a bit worried for my first post here.
What I meant with the first post was just about verbatim copying code including the JavaDocs.
I of course certainly do not take credit for simple API design concepts. :)

Cheers,
Kai

**Comment by elect86** [comment]
Hey Kay, sorry for the late reply, yeah you are right

I just felt so guilty that I overreacted :p

Thanks for your message though :)

Have a nice we!
